const Words = [
  "maintain",
  "survivability",
  "operator",
  "inter-weapon system awareness",
  "autonomous",
  "kinetic targeting",
  "manual",
  "arms",
  "rotation",
  "economy of motion",
  "maintained",
  "utilizing",
  "centrifugal force",
  "rapid",
  "jettisoning",
  "ammunition feeding device",
  "magazine",
  "ammunition hand off",
  "critical",
  "attack capabilities",
  "high speed, low drag",
  "leveraging",
  "synchronizing",
  "capabilities",
  "primary component level",
  "requires less time and less steps",
  "introducing",
  "secondary",
  "munitions delivery device",
  "kill chain",
  "ultimately",
  "reducing friction",
  "within an operator's",
  "decision cycle",
  "when prioritizing",
  "kinetic options",
  "render defensive enablers ineffective",
  "integrating improved methodologies",
  "produces",
  "a mechanism to deny",
  "and",
  "bypass an adversary's",
  "asymmetric battle space",
  "advantage",
  "when encountering",
  "tango",
  "target",
  "reduced lateral signature",
  "immediate",
  "terminal",
  "effects",
  "can prove difficult",
  "by targeting the",
  "body's",
  "central stability junction",
  "structural corruption",
  "is induced with ease",
  "regardless of the target's orientation",
  "slicing the pie",
  "can be used as an",
  "anti-access",
  "area denial advantage",
  "as a proactive countermeasure",
  "against red force",
  "vertical domination",
  "is also an option",
  "reduced sized targets",
  "are a value added",
  "force multiplier",
  "in any systemic training package",
  "diminished target unit",
  "allows the individual operator",
  "to zero their weapon system",
  "where distances are limited",
  "by range space",
  "ability to neutralize",
  "target at 1 yard",
  "guarantees",
  "the same skill and ability",
  "kinetically strike",
  "the equivalent sized target",
  "at 500 yards",
  "clear understanding",
  "is often hampered",
  "by tacit assumptions and urban myths",
  "for example",
  "a cone of deviation",
  "that distance would introduce",
  "extensive multi-tier assessment",
  "proven counter conclusive",
  "has shown that using",
  "target system",
  "individual kinetic capabilities",
  "can be used to fully replace",
  "long range marksmanship initiatives",
  "drill",
  "audible synaptic response module",
  "operator",
  "advance and engage all targets in tactical order",
  "within designated weapon system deployment area",
  "target matrix",
  "aligned to replicate",
  "real world inner and outer global conflicts",
  "assaulter assets",
  "diversified threat environment",
  "encompassing terrestrial or extra terrestrial threats",
  "standard kinetic response",
  "yielding a positive effect on target",
  "SOP",
  "to utilize the drill",
  "conventional gravity zones",
  "immobilizes the target",
  "cascading system failure",
  "mobility exploitation",
  "follow up evaluation",
  "ballistic tasking",
  "depending on operator's",
  "munitions platform",
  "ordinance delivery system",
  "battle operations spectrum",
  "can be augmented",
  "maximum impact",
  "combatives package",
  "combat weapons platform",
  "actionable upgrades",
  "optical target acquisition systems",
  "sub MOA accuracy",
  "weapon system",
  "field trials",
  "swift asymmetric advantage",
  "achieving precision effects",
  "total force construct domination",
  "cutting edge",
  "unconventional",
  "automated battle system",
  "paradigm shift",
  "core competences",
  "anti-personnel",
  "eradication solutions",
  "effective employment calculations must be made",
  "using either analog or digital means",
  "bringing to bear",
  "maximum accuracy",
  "fight",
  "stopping potential",
  "unsighted target discrimination",
  "correct use of",
  "blind fire",
  "is a low risk high yield tactic",
  "that delivers game changing potential",
  "for asymmetric battle space supremacy",
  "residual operational capability",
  "ground  assets",
  "theater level interoperability",
  "compatibility",
  "and integration issues",
  "are minimized",
  "allowing ease of",
  "organizational and multi-level communication",
  "operating within",
  "permissive threat matrix",
  "combat effective blind fire",
  "allows an individual operator to",
  "maintain a more positive battle space",
  "assimilation posture"
];

export default Words;
